import type { WorkStandard, AnalysisResult, Template } from "@/types";

export function generateDemoWorkStandard(projectId: string): WorkStandard {
  return {
    id: `ws-${projectId}`,
    projectId,
    title: "円テーブル回転精度検査 作業標準書",
    documentNumber: "WS-INS-CRT320-001",
    version: "1.2",
    revisionHistory: [
      { version: "1.0", date: "2026-02-01", author: "田中 太郎", changes: "初版作成" },
      { version: "1.1", date: "2026-02-15", author: "鈴木 花子", changes: "測定方法の詳細追加" },
      { version: "1.2", date: "2026-03-10", author: "田中 太郎", changes: "安全注意事項の追加" },
    ],
    header: {
      processName: "円テーブル回転精度検査",
      machineName: "CNCロータリーテーブル",
      machineModel: "CRT-320",
      department: "品質管理部",
      applicableProducts: ["CRT-320", "CRT-320A", "CRT-320B"],
      requiredSkillLevel: "intermediate",
      requiredPPE: ["安全メガネ", "作業手袋", "安全靴"],
      prerequisites: [
        "検査機器の校正が有効期間内であること",
        "テーブル表面が清掃されていること",
        "環境温度が20±2℃であること",
      ],
    },
    steps: [
      {
        id: "step-1",
        stepNumber: 1,
        title: "検査準備・環境確認",
        description: "検査環境の温度・湿度を確認し、検査機器を準備する",
        detailedInstructions:
          "1. 室温が20±2℃の範囲内であることを温度計で確認する\n2. 湿度が65%以下であることを確認する\n3. ダイヤルゲージ・マスターリングを準備する\n4. 検査成績書のフォームを用意する",
        keyPoints: [
          "温度安定後30分以上経過してから測定開始",
          "測定器の校正期限を必ず確認",
        ],
        cautions: ["素手でテーブル面に触れない（体温の影響を防ぐ）"],
        thumbnailUrl: "/api/placeholder/step1.jpg",
        videoTimestamp: { start: 0, end: 45 },
        estimatedTime: 300,
        tools: ["温度計", "湿度計", "ダイヤルゲージ（0.001mm）", "マスターリング"],
        measurements: [
          {
            parameter: "環境温度",
            nominalValue: 20,
            tolerance: { upper: 2, lower: -2 },
            unit: "℃",
            instrument: "デジタル温度計",
          },
        ],
        annotations: [],
        category: "preparation",
      },
      {
        id: "step-2",
        stepNumber: 2,
        title: "ダイヤルゲージのセッティング",
        description: "テーブル面にダイヤルゲージを設置し、ゼロセットを行う",
        detailedInstructions:
          "1. マグネットスタンドをテーブル基準面に設置\n2. ダイヤルゲージをテーブル外周面に接触させる\n3. 測定子の予圧を0.3〜0.5mm確保する\n4. ダイヤルゲージをゼロにセットする",
        keyPoints: [
          "測定子はテーブル中心に対して直角に当てる",
          "予圧は必ず規定範囲内に設定",
        ],
        cautions: [
          "セッティング時にテーブル面を傷つけないよう注意",
          "マグネットスタンドは確実に固定されていることを確認",
        ],
        thumbnailUrl: "/api/placeholder/step2.jpg",
        videoTimestamp: { start: 45, end: 120 },
        estimatedTime: 180,
        tools: ["ダイヤルゲージ（0.001mm）", "マグネットスタンド"],
        annotations: [
          {
            id: "ann-1",
            type: "arrow",
            x: 45,
            y: 55,
            width: 15,
            height: 5,
            label: "測定子の接触点",
            color: "#ef4444",
          },
          {
            id: "ann-2",
            type: "circle",
            x: 60,
            y: 40,
            width: 10,
            height: 10,
            label: "ゼロセット確認",
            color: "#22c55e",
          },
        ],
        category: "preparation",
      },
      {
        id: "step-3",
        stepNumber: 3,
        title: "回転精度測定（テーブル面振れ）",
        description: "テーブルを360°回転させながら面振れを測定する",
        detailedInstructions:
          "1. テーブルをゆっくり手動で360°回転させる\n2. ダイヤルゲージの最大値・最小値を記録する\n3. 振れ幅（最大値−最小値）を算出する\n4. 測定を3回繰り返す\n5. 3回の平均値を最終結果とする",
        keyPoints: [
          "回転は一定速度で行う（約10秒/回転）",
          "逆転させて測定しない（バックラッシュの影響）",
          "3回の再現性を確認すること",
        ],
        cautions: ["急激な回転操作を行わない"],
        thumbnailUrl: "/api/placeholder/step3.jpg",
        videoTimestamp: { start: 120, end: 300 },
        estimatedTime: 600,
        tools: ["ダイヤルゲージ（0.001mm）"],
        measurements: [
          {
            parameter: "テーブル面振れ",
            nominalValue: 0,
            tolerance: { upper: 0.005, lower: 0 },
            unit: "mm",
            instrument: "ダイヤルゲージ",
          },
        ],
        annotations: [
          {
            id: "ann-3",
            type: "arrow",
            x: 30,
            y: 50,
            width: 40,
            height: 5,
            label: "回転方向",
            color: "#3b82f6",
          },
        ],
        qualityCheck: "面振れ≦0.005mm",
        category: "measurement",
      },
      {
        id: "step-4",
        stepNumber: 4,
        title: "回転精度測定（外周振れ）",
        description: "テーブル外周面の振れを測定する",
        detailedInstructions:
          "1. ダイヤルゲージの測定子をテーブル外周面に移動\n2. 同様に360°回転させて測定\n3. 振れ幅を記録\n4. 3回測定して平均値を算出",
        keyPoints: [
          "外周面の測定高さを記録すること",
          "テーブル面測定と同じ条件で実施",
        ],
        cautions: [],
        thumbnailUrl: "/api/placeholder/step4.jpg",
        videoTimestamp: { start: 300, end: 480 },
        estimatedTime: 600,
        tools: ["ダイヤルゲージ（0.001mm）", "マグネットスタンド"],
        measurements: [
          {
            parameter: "テーブル外周振れ",
            nominalValue: 0,
            tolerance: { upper: 0.008, lower: 0 },
            unit: "mm",
            instrument: "ダイヤルゲージ",
          },
        ],
        annotations: [],
        qualityCheck: "外周振れ≦0.008mm",
        category: "measurement",
      },
      {
        id: "step-5",
        stepNumber: 5,
        title: "割出し精度測定",
        description: "テーブルの割出し精度を各角度で測定する",
        detailedInstructions:
          "1. ロータリーエンコーダをテーブルに設置\n2. 0°、90°、180°、270°の各位置で位置決めする\n3. 各位置での偏差を記録する\n4. 正転・逆転でそれぞれ測定\n5. 結果を検査成績書に記入",
        keyPoints: [
          "各角度で安定してから読み取る（3秒以上待つ）",
          "正転と逆転の差がバックラッシュ量",
        ],
        cautions: ["テーブルの電源が入っていることを確認"],
        thumbnailUrl: "/api/placeholder/step5.jpg",
        videoTimestamp: { start: 480, end: 720 },
        estimatedTime: 900,
        tools: ["ロータリーエンコーダ", "デジタル表示器"],
        measurements: [
          {
            parameter: "割出し精度",
            nominalValue: 0,
            tolerance: { upper: 10, lower: -10 },
            unit: "秒",
            instrument: "ロータリーエンコーダ",
          },
        ],
        annotations: [],
        qualityCheck: "割出し精度≦±10秒",
        category: "measurement",
      },
      {
        id: "step-6",
        stepNumber: 6,
        title: "検査結果の記録・判定",
        description: "全測定結果を記録し、合否判定を行う",
        detailedInstructions:
          "1. 全測定データを検査成績書に記入\n2. 各項目の合否判定を行う\n3. 不合格項目がある場合は再測定または是正処置\n4. 検査員の署名と日付を記入\n5. 上長の承認を得る",
        keyPoints: [
          "データの転記ミスがないか再確認",
          "不合格時は直ちに上長に報告",
        ],
        cautions: [],
        thumbnailUrl: "/api/placeholder/step6.jpg",
        videoTimestamp: { start: 720, end: 840 },
        estimatedTime: 300,
        tools: ["検査成績書", "ボールペン（黒）"],
        annotations: [],
        category: "inspection",
      },
      {
        id: "step-7",
        stepNumber: 7,
        title: "後片付け・清掃",
        description: "測定器具の片付けとテーブルの清掃を行う",
        detailedInstructions:
          "1. ダイヤルゲージ・スタンドを収納ケースに戻す\n2. テーブル面を防錆油を含むウエスで拭く\n3. テーブルに防錆カバーをかける\n4. 作業エリアを清掃する",
        keyPoints: ["防錆処理を忘れないこと", "測定器は衝撃を与えないよう丁寧に扱う"],
        cautions: ["防錆油は適量を使用（過剰塗布は次回測定時に影響）"],
        thumbnailUrl: "/api/placeholder/step7.jpg",
        videoTimestamp: { start: 840, end: 920 },
        estimatedTime: 300,
        tools: ["防錆油", "ウエス", "防錆カバー"],
        annotations: [],
        category: "cleanup",
      },
    ],
    safetyNotes: [
      {
        id: "safety-1",
        severity: "warning",
        title: "回転部への巻き込み注意",
        description:
          "テーブル回転中は手や衣服が巻き込まれないよう十分注意してください。長袖は手首で留めてください。",
        relatedSteps: [3, 4, 5],
        icon: "alert-triangle",
      },
      {
        id: "safety-2",
        severity: "caution",
        title: "重量物の取り扱い",
        description:
          "マスターリングやフィクスチャは重量物です。持ち上げる際は正しい姿勢で行ってください。",
        relatedSteps: [1, 2],
        icon: "shield",
      },
      {
        id: "safety-3",
        severity: "info",
        title: "保護具の着用",
        description: "作業中は安全メガネ、作業手袋、安全靴を着用してください。",
        relatedSteps: [1, 2, 3, 4, 5, 6, 7],
        icon: "hard-hat",
      },
    ],
    qualityCheckpoints: [
      {
        id: "qc-1",
        stepNumber: 1,
        checkItem: "環境温度",
        method: "温度計で測定",
        standard: "20±2℃",
        acceptanceCriteria: "18〜22℃の範囲内",
        measuringInstrument: "デジタル温度計",
        frequency: "検査開始時",
        recordRequired: true,
      },
      {
        id: "qc-2",
        stepNumber: 3,
        checkItem: "テーブル面振れ",
        method: "ダイヤルゲージ測定",
        standard: "≦0.005mm",
        acceptanceCriteria: "振れ幅0.005mm以下",
        measuringInstrument: "ダイヤルゲージ（0.001mm）",
        frequency: "3回測定の平均",
        recordRequired: true,
      },
      {
        id: "qc-3",
        stepNumber: 4,
        checkItem: "テーブル外周振れ",
        method: "ダイヤルゲージ測定",
        standard: "≦0.008mm",
        acceptanceCriteria: "振れ幅0.008mm以下",
        measuringInstrument: "ダイヤルゲージ（0.001mm）",
        frequency: "3回測定の平均",
        recordRequired: true,
      },
      {
        id: "qc-4",
        stepNumber: 5,
        checkItem: "割出し精度",
        method: "ロータリーエンコーダ測定",
        standard: "≦±10秒",
        acceptanceCriteria: "各角度で±10秒以内",
        measuringInstrument: "ロータリーエンコーダ",
        frequency: "各角度（0°/90°/180°/270°）",
        recordRequired: true,
      },
    ],
    toolsRequired: [
      {
        id: "tool-1",
        name: "ダイヤルゲージ",
        specification: "最小目盛0.001mm、測定範囲5mm",
        quantity: 1,
        category: "measuring",
      },
      {
        id: "tool-2",
        name: "マグネットスタンド",
        specification: "微調整機構付き",
        quantity: 1,
        category: "fixture",
      },
      {
        id: "tool-3",
        name: "ロータリーエンコーダ",
        specification: "分解能0.1秒",
        quantity: 1,
        category: "measuring",
      },
      {
        id: "tool-4",
        name: "デジタル温度計",
        specification: "分解能0.1℃",
        quantity: 1,
        category: "measuring",
      },
      {
        id: "tool-5",
        name: "防錆油",
        specification: "速乾性タイプ",
        quantity: 1,
        category: "consumable",
      },
      {
        id: "tool-6",
        name: "安全メガネ",
        specification: "JIS規格適合品",
        quantity: 1,
        category: "ppe",
      },
    ],
    estimatedTotalTime: 3180,
    createdAt: "2026-02-01T09:00:00Z",
    updatedAt: "2026-03-10T15:30:00Z",
    approvedBy: "品質管理部長 山田次郎",
    approvedAt: "2026-03-10T15:30:00Z",
  };
}

export function generateDemoAnalysisResult(): AnalysisResult {
  return {
    scenes: [
      {
        id: "scene-1",
        startTime: 0,
        endTime: 45,
        description: "検査環境の準備と機器の確認",
        confidence: 0.92,
        thumbnailUrl: "/api/placeholder/scene1.jpg",
        category: "preparation",
      },
      {
        id: "scene-2",
        startTime: 45,
        endTime: 120,
        description: "ダイヤルゲージの取り付けとゼロセット",
        confidence: 0.88,
        thumbnailUrl: "/api/placeholder/scene2.jpg",
        category: "preparation",
      },
      {
        id: "scene-3",
        startTime: 120,
        endTime: 300,
        description: "テーブル面振れの測定作業",
        confidence: 0.95,
        thumbnailUrl: "/api/placeholder/scene3.jpg",
        category: "measurement",
      },
      {
        id: "scene-4",
        startTime: 300,
        endTime: 480,
        description: "テーブル外周振れの測定作業",
        confidence: 0.91,
        thumbnailUrl: "/api/placeholder/scene4.jpg",
        category: "measurement",
      },
      {
        id: "scene-5",
        startTime: 480,
        endTime: 720,
        description: "割出し精度の測定と記録",
        confidence: 0.87,
        thumbnailUrl: "/api/placeholder/scene5.jpg",
        category: "measurement",
      },
      {
        id: "scene-6",
        startTime: 720,
        endTime: 840,
        description: "検査結果の記録と合否判定",
        confidence: 0.9,
        thumbnailUrl: "/api/placeholder/scene6.jpg",
        category: "inspection",
      },
      {
        id: "scene-7",
        startTime: 840,
        endTime: 920,
        description: "片付けと防錆処理",
        confidence: 0.93,
        thumbnailUrl: "/api/placeholder/scene7.jpg",
        category: "cleanup",
      },
    ],
    ocrTexts: [
      {
        timestamp: 15,
        text: "環境温度: 20.3℃",
        boundingBox: { x: 10, y: 80, width: 30, height: 5 },
        confidence: 0.96,
      },
      {
        timestamp: 180,
        text: "0.003mm",
        boundingBox: { x: 55, y: 40, width: 15, height: 5 },
        confidence: 0.94,
      },
      {
        timestamp: 500,
        text: "割出し角度: 90.000°",
        boundingBox: { x: 40, y: 30, width: 25, height: 5 },
        confidence: 0.91,
      },
    ],
    detectedTools: [
      "ダイヤルゲージ",
      "マグネットスタンド",
      "ロータリーエンコーダ",
      "温度計",
      "ウエス",
    ],
    detectedActions: [
      "機器セッティング",
      "ゼロ点調整",
      "テーブル回転操作",
      "数値読み取り",
      "記録作業",
      "清掃作業",
    ],
    suggestedSteps: [
      {
        title: "検査準備・環境確認",
        description: "検査環境の温度・湿度を確認し、検査機器を準備する",
        keyPoints: ["温度安定後30分以上経過してから測定開始"],
        startTime: 0,
        endTime: 45,
        category: "preparation",
        confidence: 0.92,
      },
      {
        title: "ダイヤルゲージのセッティング",
        description: "テーブル面にダイヤルゲージを設置し、ゼロセットを行う",
        keyPoints: ["測定子はテーブル中心に対して直角に当てる"],
        startTime: 45,
        endTime: 120,
        category: "preparation",
        confidence: 0.88,
      },
      {
        title: "回転精度測定（テーブル面振れ）",
        description: "テーブルを360°回転させながら面振れを測定する",
        keyPoints: ["回転は一定速度で行う", "3回測定して平均値を算出"],
        startTime: 120,
        endTime: 300,
        category: "measurement",
        confidence: 0.95,
      },
      {
        title: "回転精度測定（外周振れ）",
        description: "テーブル外周面の振れを測定する",
        keyPoints: ["外周面の測定高さを記録すること"],
        startTime: 300,
        endTime: 480,
        category: "measurement",
        confidence: 0.91,
      },
      {
        title: "割出し精度測定",
        description: "テーブルの割出し精度を各角度で測定する",
        keyPoints: ["各角度で安定してから読み取る"],
        startTime: 480,
        endTime: 720,
        category: "measurement",
        confidence: 0.87,
      },
      {
        title: "検査結果の記録・判定",
        description: "全測定結果を記録し、合否判定を行う",
        keyPoints: ["データの転記ミスがないか再確認"],
        startTime: 720,
        endTime: 840,
        category: "inspection",
        confidence: 0.9,
      },
      {
        title: "後片付け・清掃",
        description: "測定器具の片付けとテーブルの清掃を行う",
        keyPoints: ["防錆処理を忘れないこと"],
        startTime: 840,
        endTime: 920,
        category: "cleanup",
        confidence: 0.93,
      },
    ],
    processingTime: 45.2,
  };
}

export const inspectionTemplates: Template[] = [
  {
    id: "tmpl-rotary-inspection",
    name: "円テーブル精度検査",
    description: "CNC工作機械用円テーブルの精度検査用テンプレート",
    category: "inspection",
    presetSteps: [
      { title: "検査準備", category: "preparation" },
      { title: "測定器セッティング", category: "preparation" },
      { title: "精度測定", category: "measurement" },
      { title: "結果記録・判定", category: "inspection" },
      { title: "後片付け", category: "cleanup" },
    ],
    presetSafetyNotes: [
      { severity: "warning", title: "回転部への巻き込み注意" },
      { severity: "info", title: "保護具の着用" },
    ],
    presetTools: [
      { name: "ダイヤルゲージ", category: "measuring" },
      { name: "マグネットスタンド", category: "fixture" },
    ],
    presetQualityCheckpoints: [
      { checkItem: "環境温度確認", method: "温度計で測定" },
      { checkItem: "精度測定", method: "ダイヤルゲージ測定" },
    ],
  },
  {
    id: "tmpl-assembly",
    name: "組立作業標準",
    description: "一般的な組立工程用テンプレート",
    category: "assembly",
    presetSteps: [
      { title: "部品確認", category: "preparation" },
      { title: "組立作業", category: "operation" },
      { title: "品質検査", category: "inspection" },
      { title: "完了処理", category: "cleanup" },
    ],
    presetSafetyNotes: [
      { severity: "caution", title: "重量物の取り扱い注意" },
    ],
    presetTools: [],
    presetQualityCheckpoints: [],
  },
  {
    id: "tmpl-maintenance",
    name: "定期メンテナンス",
    description: "設備の定期メンテナンス用テンプレート",
    category: "maintenance",
    presetSteps: [
      { title: "事前確認・ロックアウト", category: "safety-check" },
      { title: "点検作業", category: "inspection" },
      { title: "部品交換・調整", category: "operation" },
      { title: "動作確認", category: "inspection" },
      { title: "復旧・記録", category: "cleanup" },
    ],
    presetSafetyNotes: [
      { severity: "danger", title: "電源ロックアウト必須" },
      { severity: "warning", title: "高温部注意" },
    ],
    presetTools: [],
    presetQualityCheckpoints: [],
  },
];
